### ISSUE TITLE
Error while running after installing the package.

### ISSUE THREAD

**Issue by letmestaybehind** [bqbooster/dbt-bigquery-monitoring#4]
I ran into this error as i installed the package, can you have a look.

`14:12:02  [WARNING]: Did not find matching node for patch with name 'write_api_timeline_by_organization' in the 'models' section of file 'models/base/google/write_api/information_schema_write_api_timeline_by_organization.yml'
`
```
Compilation Error
  dbt found two resources with the database representation "`project`.`dataset`.`with_better_pricing_on_physical_billing_model`".
  dbt cannot create two resources with identical database representations. To fix this,
  change the configuration of one of these resources:
  - model.dbt_bigquery_monitoring.dataset_with_better_pricing_on_physical_billing_model (models/storage/datamart/dataset_with_better_pricing_on_physical_billing_model.sql)
  - model.dbt_bigquery_monitoring.table_with_better_pricing_on_physical_billing_model (models/storage/datamart/table_with_better_pricing_on_physical_billing_model.sql)
```

**Comment by Kayrnt** [comment]
Hello @letmestaybehind, thanks for the report!

I'll have a look at it later today.
I've a fairly [big changes](https://github.com/bqbooster/dbt-bigquery-monitoring/pull/3/files) that was in standby (as I'm working on other projects too) that I might ship as well.

Which version did you use? 0.4.0?
What version of dbt are you using?

**Comment by letmestaybehind** [comment]
Thank you for the quick response!

I have used the version 1.8.3, registered with the bigquery adapter 1.8.2. And yes, i used your version 0.4.0.

**Comment by github-christophe-oudar** [comment]
Could you try running (adapted to your gcp project):
`DBT_BQ_MONITORING_GCP_PROJECTS="['your_gcp_project']" dbt run -s tag:dbt-bigquery-monitoring -t prod`
?

**Comment by letmestaybehind** [comment]
```
15:27:34  [WARNING]: Did not find matching node for patch with name 'table_storage_usage_timeline_by_organization' in the 'models' section of file 'models/base/google/tables/information_schema_table_storage_usage_timeline_by_organization.yml'
15:27:34  [WARNING]: Did not find matching node for patch with name 'table_snapshots' in the 'models' section of file 'models/base/google/tables/information_schema_table_snapshots.yml'
15:27:34  [WARNING]: Did not find matching node for patch with name 'table_options' in the 'models' section of file 'models/base/google/tables/information_schema_table_options.yml'
15:27:34  [WARNING]: Did not find matching node for patch with name 'table_storage_usage_timeline' in the 'models' section of file 'models/base/google/tables/information_schema_table_storage_usage_timeline.yml'
15:27:34  [WARNING]: Did not find matching node for patch with name 'table_storage' in the 'models' section of file 'models/base/google/tables/information_schema_table_storage.yml'
15:27:34  [WARNING]: Did not find matching node for patch with name 'tables' in the 'models' section of file 'models/base/google/tables/information_schema_tables.yml'
15:27:34  [WARNING]: Did not find matching node for patch with name 'table_constraints' in the 'models' section of file 'models/base/google/tables/information_schema_table_constraints.yml'
15:27:34  [WARNING]: Did not find matching node for patch with name 'columns' in the 'models' section of file 'models/base/google/tables/information_schema_columns.yml'
15:27:34  [WARNING]: Did not find matching node for patch with name 'table_storage_by_organization' in the 'models' section of file 'models/base/google/tables/information_schema_table_storage_by_organization.yml'
15:27:34  [WARNING]: Did not find matching node for patch with name 'constraint_column_usage' in the 'models' section of file 'models/base/google/tables/information_schema_constraint_column_usage.yml'
15:27:34  [WARNING]: Did not find matching node for patch with name 'key_column_usage' in the 'models' section of file 'models/base/google/tables/information_schema_key_column_usage.yml'
15:27:34  [WARNING]: Did not find matching node for patch with name 'column_field_paths' in the 'models' section of file 'models/base/google/tables/information_schema_column_field_paths.yml'
15:27:34  [WARNING]: Did not find matching node for patch with name 'organization_options' in the 'models' section of file 'models/base/google/configuration/information_schema_organization_options.yml'
15:27:34  [WARNING]: Did not find matching node for patch with name 'effective_project_options' in the 'models' section of file 'models/base/google/configuration/information_schema_effective_project_options.yml'
15:27:34  [WARNING]: Did not find matching node for patch with name 'project_options' in the 'models' section of file 'models/base/google/configuration/information_schema_project_options.yml'
15:27:34  [WARNING]: Did not find matching node for patch with name 'organization_options_changes' in the 'models' section of file 'models/base/google/configuration/information_schema_organization_options_changes.yml'
15:27:34  [WARNING]: Did not find matching node for patch with name 'project_options_changes' in the 'models' section of file 'models/base/google/configuration/information_schema_project_options_changes.yml'
15:27:34  [WARNING]: Did not find matching node for patch with name 'bi_capacities' in the 'models' section of file 'models/base/google/bi_engine/information_schema_bi_capacities.yml'
15:27:34  [WARNING]: Did not find matching node for patch with name 'bi_capacity_changes' in the 'models' section of file 'models/base/google/bi_engine/information_schema_bi_capacity_changes.yml'
15:27:34  [WARNING]: Did not find matching node for patch with name 'search_indexes' in the 'models' section of file 'models/base/google/search_indexes/information_schema_search_indexes.yml'
15:27:34  [WARNING]: Did not find matching node for patch with name 'search_index_columns' in the 'models' section of file 'models/base/google/search_indexes/information_schema_search_index_columns.yml'
15:27:34  [WARNING]: Did not find matching node for patch with name 'reservations_timeline' in the 'models' section of file 'models/base/google/reservations/information_schema_reservations_timeline.yml'
15:27:34  [WARNING]: Did not find matching node for patch with name 'assignment_changes' in the 'models' section of file 'models/base/google/reservations/information_schema_assignment_changes.yml'
15:27:34  [WARNING]: Did not find matching node for patch with name 'assignments' in the 'models' section of file 'models/base/google/reservations/information_schema_assignments.yml'
15:27:34  [WARNING]: Did not find matching node for patch with name 'reservation_changes' in the 'models' section of file 'models/base/google/reservations/information_schema_reservation_changes.yml'
15:27:34  [WARNING]: Did not find matching node for patch with name 'capacity_commitment_changes' in the 'models' section of file 'models/base/google/reservations/information_schema_capacity_commitment_changes.yml'
15:27:34  [WARNING]: Did not find matching node for patch with name 'reservations' in the 'models' section of file 'models/base/google/reservations/information_schema_reservations.yml'
15:27:34  [WARNING]: Did not find matching node for patch with name 'capacity_commitments' in the 'models' section of file 'models/base/google/reservations/information_schema_capacity_commitments.yml'
15:27:34  [WARNING]: Did not find matching node for patch with name 'shared_dataset_usage' in the 'models' section of file 'models/base/google/datasets/information_schema_shared_dataset_usage.yml'
15:27:34  [WARNING]: Did not find matching node for patch with name 'schemata' in the 'models' section of file 'models/base/google/datasets/information_schema_schemata.yml'
15:27:34  [WARNING]: Did not find matching node for patch with name 'schemata_replicas' in the 'models' section of file 'models/base/google/datasets/information_schema_schemata_replicas.yml'
15:27:34  [WARNING]: Did not find matching node for patch with name 'schemata_links' in the 'models' section of file 'models/base/google/datasets/information_schema_links.yml'
15:27:34  [WARNING]: Did not find matching node for patch with name 'schemata_options' in the 'models' section of file 'models/base/google/datasets/information_schema_schemata_options.yml'
15:27:34  [WARNING]: Did not find matching node for patch with name 'vector_index_columns' in the 'models' section of file 'models/base/google/vector_indexes/information_schema_vector_index_columns.yml'
15:27:34  [WARNING]: Did not find matching node for patch with name 'vector_index_options' in the 'models' section of file 'models/base/google/vector_indexes/information_schema_vector_index_options.yml'
15:27:34  [WARNING]: Did not find matching node for patch with name 'vector_indexes' in the 'models' section of file 'models/base/google/vector_indexes/information_schema_vector_indexes.yml'
15:27:34  [WARNING]: Did not find matching node for patch with name 'jobs_timeline' in the 'models' section of file 'models/base/google/jobs_timeline/information_schema_jobs_timeline.yml'
15:27:34  [WARNING]: Did not find matching node for patch with name 'jobs_timeline_by_organization' in the 'models' section of file 'models/base/google/jobs_timeline/information_schema_jobs_timeline_by_organization.yml'
15:27:34  [WARNING]: Did not find matching node for patch with name 'jobs_timeline_by_user' in the 'models' section of file 'models/base/google/jobs_timeline/information_schema_jobs_timeline_by_user.yml'
15:27:34  [WARNING]: Did not find matching node for patch with name 'jobs_timeline_by_folder' in the 'models' section of file 'models/base/google/jobs_timeline/information_schema_jobs_timeline_by_folder.yml'
15:27:34  [WARNING]: Did not find matching node for patch with name 'streaming_timeline_by_organization' in the 'models' section of file 'models/base/google/streaming/information_schema_streaming_timeline_by_organization.yml'
15:27:34  [WARNING]: Did not find matching node for patch with name 'streaming_timeline_by_folder' in the 'models' section of file 'models/base/google/streaming/information_schema_streaming_timeline_by_folder.yml'
15:27:34  [WARNING]: Did not find matching node for patch with name 'streaming_timeline' in the 'models' section of file 'models/base/google/streaming/information_schema_streaming_timeline.yml'
15:27:34  [WARNING]: Did not find matching node for patch with name 'routine' in the 'models' section of file 'models/base/google/routines/information_schema_routines.yml'
15:27:34  [WARNING]: Did not find matching node for patch with name 'parameters' in the 'models' section of file 'models/base/google/routines/information_schema_parameters.yml'
15:27:34  [WARNING]: Did not find matching node for patch with name 'routine_options' in the 'models' section of file 'models/base/google/routines/information_schema_routine_options.yml'
15:27:34  [WARNING]: Did not find matching node for patch with name 'sessions_by_project' in the 'models' section of file 'models/base/google/sessions/information_schema_sessions_by_project.yml'
15:27:34  [WARNING]: Did not find matching node for patch with name 'sessions_by_user' in the 'models' section of file 'models/base/google/sessions/information_schema_sessions_by_user.yml'
15:27:34  [WARNING]: Did not find matching node for patch with name 'object_privileges' in the 'models' section of file 'models/base/google/access_control/information_schema_object_privileges.yml'
15:27:34  [WARNING]: Did not find matching node for patch with name 'jobs' in the 'models' section of file 'models/base/google/jobs/information_schema_jobs.yml'
15:27:34  [WARNING]: Did not find matching node for patch with name 'jobs_by_user' in the 'models' section of file 'models/base/google/jobs/information_schema_jobs_by_user.yml'
15:27:34  [WARNING]: Did not find matching node for patch with name 'jobs_by_folder' in the 'models' section of file 'models/base/google/jobs/information_schema_jobs_by_folder.yml'
15:27:34  [WARNING]: Did not find matching node for patch with name 'jobs_by_organization' in the 'models' section of file 'models/base/google/jobs/information_schema_jobs_by_organization.yml'
15:27:34  [WARNING]: Did not find matching node for patch with name 'jobs_by_project' in the 'models' section of file 'models/base/google/jobs/information_schema_jobs_by_project.yml'
15:27:34  [WARNING]: Did not find matching node for patch with name 'views' in the 'models' section of file 'models/base/google/views/information_schema_views.yml'
15:27:34  [WARNING]: Did not find matching node for patch with name 'materialized_views' in the 'models' section of file 'models/base/google/views/information_schema_materialized_views.yml'
15:27:34  [WARNING]: Did not find matching node for patch with name 'write_api_timeline' in the 'models' section of file 'models/base/google/write_api/information_schema_write_api_timeline.yml'
15:27:34  [WARNING]: Did not find matching node for patch with name 'write_api_timeline_by_organization' in the 'models' section of file 'models/base/google/write_api/information_schema_write_api_timeline_by_organization.yml'
15:27:34  [WARNING]: Did not find matching node for patch with name 'write_api_timeline_by_folder' in the 'models' section of file 'models/base/google/write_api/information_schema_write_api_timeline_by_folder.yml'
```

```
dbt cannot create two resources with identical database representations. To fix this,
  change the configuration of one of these resources:
  - model.dbt_bigquery_monitoring.jobs_with_cost (models/base/jobs_with_cost.sql)
  - model.dbt_bigquery_monitoring.storage_with_cost (models/base/storage_with_cost.sql)
```

**Comment by Kayrnt** [comment]
I think I know why you have warnings, I'll fix it though I'm curious I don't see them.
However it doesn't block me to run the package.
I might double check later today if I can reproduce it as an installed package instead of running the package directly (I'm running the models directly without installing it in another dbt project).

**Comment by letmestaybehind** [comment]
Sure, let me know if you find something. I would be happy to also collaborate in future as i see scope in this project!

**Comment by Kayrnt** [comment]
Sure feel free to create an issue with what you need.
I'll create a sample working dbt project with the package and if it works you might be able to compare the settings (and if it doesn't work I can fix it👌)

**Comment by Kayrnt** [comment]
Ok I managed to reproduce the issues in dbt 1.8.X, I was using dbt 1.7.X while developing, I'll be looking into fixing the project for dbt 1.8.X

**Comment by letmestaybehind** [comment]
Thank you for keeping me updated! Very eager to test this out as soon as it is released.

**Comment by Kayrnt** [comment]
Ok it's now working on my end.
Two issues in my opinion:
- I renamed Google based models to limit the risk of model name collision in the previous latest version (0.5.0) and it wasn't aligned anymore with the actual model. It's now fixed.
- I published 0.5.0 using a tag... but I didn't merge it on the main and it looks like it wasn't working as intended when pulled using dbt packages.

Anyway I published 0.5.1 which should work for you too🙏

**Comment by letmestaybehind** [comment]
Thank you for the detailed updated, i will try it on my end and get back to you!

**Comment by letmestaybehind** [comment]
On running the below command, i still received the error, but fewer than before. The version i used was 0.5.1

`DBT_BQ_MONITORING_GCP_PROJECTS="['your_gcp_project']" dbt run -s tag:dbt-bigquery-monitoring `

```
22:10:37  [WARNING]: Did not find matching node for patch with name 'information_schema_schemata_links' in the 'models' section of file 'models/base/google/datasets/information_schema_links.yml'
22:10:41  Encountered an error:
Compilation Error
  dbt found two resources with the database representation "`project`.`dataset`.`with_better_pricing_on_physical_billing_model`".
  dbt cannot create two resources with identical database representations. To fix this,
  change the configuration of one of these resources:
  - model.dbt_bigquery_monitoring.dataset_with_better_pricing_on_physical_billing_model (models/storage/datamart/dataset_with_better_pricing_on_physical_billing_model.sql)
  - model.dbt_bigquery_monitoring.table_with_better_pricing_on_physical_billing_model (models/storage/datamart/table_with_better_pricing_on_physical_billing_model.sql)
```

**Comment by Kayrnt** [comment]
Ok there's still a small fix for schemata but in my opinion, you actual issue isn't related to the extension.
```
Compilation Error
  dbt found two resources with the database representation "`project`.`dataset`.`with_better_pricing_on_physical_billing_model`".
  dbt cannot create two resources with identical database representations. To fix this,
  change the configuration of one of these resources:
  - model.dbt_bigquery_monitoring.dataset_with_better_pricing_on_physical_billing_model (models/storage/datamart/dataset_with_better_pricing_on_physical_billing_model.sql)
  - model.dbt_bigquery_monitoring.table_with_better_pricing_on_physical_billing_model (models/storage/datamart/table_with_better_pricing_on_physical_billing_model.sql)
```
My guess is that this error is caused by a dbt override macro that strip `table_` and `dataset_` from the name of the output of the table resulting in a collision.

**Comment by letmestaybehind** [comment]
Yes, i have overridden the generate_alias_name macro by adding a variable as a prefix for my models in CI. Can this be a reason?

**Comment by Kayrnt** [comment]
I wonder, I don't know what your implementation is doing but without any macro the package appears to work on my end.

**Comment by Kayrnt** [comment]
Hey 👋 
Any update on this issue?
I hope you managed to fix it 👀

**Comment by letmestaybehind** [comment]
Hey! I was not able to get it running, maybe it has something to do with the way dbt is setup on our end. But it still shows "dbt found two resources..." but lesser after you made an update. So, i believe you could still do something about it, but I hope it gets running.

**Comment by github-christophe-oudar** [comment]
I'm not sure how it's on your end but I don't know how to reproduce the problem.
If you create a new dbt project and run it as a package, maybe it would and then you would be able to pinpoint what's the settings that make dbt strip the prefix on those models.
Renaming is likely not a good idea as it would break other users usages of those datamarts.

**Comment by letmestaybehind** [comment]
This is what i have defined as vars, is this correct?

bq_region: 'europe-west3'
input_gcp_projects: [ 'jaffle_project' ]

**Comment by letmestaybehind** [comment]
Also, could it be because you are using an ephermal model, and since i have two projects, they are conflicting?

Source:
#https://stackoverflow.com/questions/78437439/dbt-conflicts-in-resource-naming-across-different-gcp-projects
#https://discourse.getdbt.com/t/error-when-same-variable-is-used-in-target-of-2-different-models/6885/3
#https://stackoverflow.com/questions/63677530/dbt-cannot-create-two-resources-with-identical-database-representations

**Comment by letmestaybehind** [comment]
Also, let me email you the custom generate_alias_name macro that is used in my project, maybe that could point out things for you?

**Comment by letmestaybehind** [comment]
Also, after removing the macro, it works! Idk what would be the workaround for this!

**Comment by Kayrnt** [comment]
Yep as expected, it's your macro.
I sent you a fix.

**Comment by letmestaybehind** [comment]
Yes, it's the macro. However, the fix still causes the same issue.

**Comment by github-christophe-oudar** [comment]
Alright I think I get it why, easy fix though

**Comment by letmestaybehind** [comment]
Fixed! Thank you once again for all the support.

**Comment by letmestaybehind** [comment]
Also, is the data loaded from inception, or how old the data is?

**Comment by github-christophe-oudar** [comment]
The default lookback window is 7 days. There's a variable to override it.
The models are incremental to keep up with previous runs.
